export interface Candidate {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  phone: string | null;
  position: string;
  status: 'nouveau' | 'en cours' | 'accepté' | 'rejeté';
  experience_years: number;
  location: string | null;
  applied_date: string;
  created_at: string;
  updated_at: string;
}

export const candidatesData: Candidate[] = [
  {
    id: '1',
    first_name: 'Jean',
    last_name: 'Dupont',
    email: 'jean.dupont@email.com',
    phone: '+33 6 12 34 56 78',
    position: 'Développeur Full Stack',
    status: 'nouveau',
    experience_years: 5,
    location: 'Paris',
    applied_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    first_name: 'Marie',
    last_name: 'Martin',
    email: 'marie.martin@email.com',
    phone: '+33 6 23 45 67 89',
    position: 'Designer UI/UX',
    status: 'en cours',
    experience_years: 3,
    location: 'Lyon',
    applied_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    first_name: 'Pierre',
    last_name: 'Bernard',
    email: 'pierre.bernard@email.com',
    phone: '+33 6 34 56 78 90',
    position: 'Chef de Projet',
    status: 'accepté',
    experience_years: 8,
    location: 'Marseille',
    applied_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    first_name: 'Sophie',
    last_name: 'Dubois',
    email: 'sophie.dubois@email.com',
    phone: '+33 6 45 67 89 01',
    position: 'Data Scientist',
    status: 'nouveau',
    experience_years: 4,
    location: 'Toulouse',
    applied_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    first_name: 'Luc',
    last_name: 'Thomas',
    email: 'luc.thomas@email.com',
    phone: '+33 6 56 78 90 12',
    position: 'DevOps Engineer',
    status: 'en cours',
    experience_years: 6,
    location: 'Nantes',
    applied_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    first_name: 'Emma',
    last_name: 'Robert',
    email: 'emma.robert@email.com',
    phone: '+33 6 67 89 01 23',
    position: 'Product Manager',
    status: 'rejeté',
    experience_years: 7,
    location: 'Bordeaux',
    applied_date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '7',
    first_name: 'Lucas',
    last_name: 'Petit',
    email: 'lucas.petit@email.com',
    phone: '+33 6 78 90 12 34',
    position: 'Développeur Frontend',
    status: 'nouveau',
    experience_years: 2,
    location: 'Lille',
    applied_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '8',
    first_name: 'Camille',
    last_name: 'Roux',
    email: 'camille.roux@email.com',
    phone: '+33 6 89 01 23 45',
    position: 'Développeur Backend',
    status: 'en cours',
    experience_years: 5,
    location: 'Strasbourg',
    applied_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '9',
    first_name: 'Thomas',
    last_name: 'Vincent',
    email: 'thomas.vincent@email.com',
    phone: '+33 6 90 12 34 56',
    position: 'QA Engineer',
    status: 'accepté',
    experience_years: 4,
    location: 'Rennes',
    applied_date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '10',
    first_name: 'Julie',
    last_name: 'Fournier',
    email: 'julie.fournier@email.com',
    phone: '+33 6 01 23 45 67',
    position: 'Scrum Master',
    status: 'nouveau',
    experience_years: 6,
    location: 'Nice',
    applied_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '11',
    first_name: 'Alexandre',
    last_name: 'Morel',
    email: 'alex.morel@email.com',
    phone: '+33 6 12 34 56 79',
    position: 'Architecte Logiciel',
    status: 'en cours',
    experience_years: 10,
    location: 'Paris',
    applied_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '12',
    first_name: 'Céline',
    last_name: 'Girard',
    email: 'celine.girard@email.com',
    phone: '+33 6 23 45 67 80',
    position: 'Business Analyst',
    status: 'nouveau',
    experience_years: 3,
    location: 'Lyon',
    applied_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
